version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - jonpearse
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.21.1
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.1
    - 5.28.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: "@babel/plugin-transform-object-assign"
    versions:
    - 7.12.13
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - jonpearse
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: sidekiq
    versions:
    - 6.2.0
  - dependency-name: awesome_print
    versions:
    - 1.9.2
  - dependency-name: puma
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: browser
    versions:
    - 5.3.1
  - dependency-name: jbuilder
    versions:
    - 2.11.0
