---
- title:  Dashboard
  route:  dashboard#show
  icon:   tachometer

- title:  Blog
  route:  blog/articles
  icon:   book
  children:
    - title:  Articles
      route:  blog/articles
    - title:  Categories
      route:  blog/categories

- title:  Work
  route:  work/projects
  icon:   building
  children:
    - title:  Projects
      route:  work/projects
    - title:  Clients
      route:  work/clients
    - title:  Technologies
      route:  work/techs
      split:  true

- title:  Media
  route:  media/media
  icon:   images
  children:
    - title: Media library
      route: media/media
#
# - title:  Site stuff
#   route:  settings/snippets
#   icon:   cog
#   children:
#     - title: Snippets
#       route: settings/snippets
#     - title: Change password
#       route: auth/password#change
#       split: true
#     - title: Two-factor auth
#       route: auth/two_factor#setup
