# This nginx configuration is used in development (see /ops/config/nginx for the
# production version).
#
# It differs to the deployed configuration (e.g. does not daemonize, logs to
# stdout), but should be logically identical.

# Run in foreground
daemon off;

events { }

http {
  # Note: When debugging nginx config change these to /dev/stdout.
  error_log /dev/null info;
  access_log /dev/null;

  include /opt/homebrew/etc/nginx/mime.types;

	# Specify upstream for 11ty
  upstream 11ty-dev {
    server localhost:3000 max_fails=0;
  }

  # --------------------------
  # Theme switch functionality
  # --------------------------

  # Map from cookie through to color-scheme value
  map $http_cookie $colour_scheme_output {
    default "light dark";

    "~*colour-scheme=force-light" "light";
    "~*colour-scheme=force-dark" "dark";
  }

  # Map theme URL to cookie value
  map $theme $theme_value {
    default "";
    "light"	"force-light";
    "dark"	"force-dark";
  }

  # Also, get a “back”
  map $http_referer $theme_referer {
    ""      /;                # fallback if Referer is stripped/empty
    default $http_referer;
  }

  server {
    # This sets $root_path (from autogenerated, gitignored file)
    include path.conf;

    listen 3080;
		include "../.build/nginx-redirects.txt";

		location / {
			proxy_pass http://11ty-dev/;

			proxy_set_header  Host $host;
			proxy_set_header  X-Real-IP $remote_addr;
			proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header  X-Forwarded-Proto $scheme;

			# Also bounce websockets
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			# THEME SWITCH: drop theme into the HTML
			sub_filter '--XSSICOLOURSCHEME:' '--colour-scheme: $colour_scheme_output';
			sub_filter_once on;
		}

		# Handle setting cookies
		location ~ ^/set-theme/(?<theme>[a-z]+)$ {
			add_header Set-Cookie "colour-scheme=$theme_value; Path=/; Secure; SameSite=Strict; Max-Age=31536000" always;
			return 302 $theme_referer;
		}
  }
}
