version: 1

update_configs:
  - package_manager:  javascript
    directory:        /
    update_schedule:  weekly
    default_assignees:
      - jonpearse

  - package_manager:  ruby:bundler
    directory:        /
    update_schedule:  weekly
    default_assignees:
      - jonpearse
